# Generated by Django 5.0.6 on 2024-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('categoria', models.TextField(choices=[('GERAL', 'Perguntas frequentes gerais'), ('PRODUTO', 'FAQ sobre produtos'), ('SERVICO', 'FAQ sobre serviços')])),
                ('palavras_chaves', models.TextField()),
                ('produto', models.TextField(choices=[('PRODUTOA', 'Produto A'), ('PRODUTOB', 'Produto B'), ('PRODUTOC', 'Produto C')])),
                ('estado', models.TextField(choices=[('ATIVO', 'Ativo'), ('ARQUIVADO', 'Arquivado')])),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('classificacao', models.IntegerField()),
                ('descricao', models.TextField()),
                ('canal_feedback', models.TextField(choices=[('EMAIL', 'email'), ('WEBSITE', 'website'), ('WHATSAPP', 'whatsapp')])),
                ('produto', models.TextField(choices=[('PRODUTOA', 'Produto A'), ('PRODUTOB', 'Produto B'), ('PRODUTOC', 'Produto C')])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('prioridade', models.TextField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')])),
                ('canal_abertura', models.TextField(choices=[('EMAIL', 'email'), ('WEBSITE', 'website'), ('WHATSAPP', 'whatsapp')])),
                ('nome_cliente', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('fila', models.TextField(choices=[('BASE', 'Base'), ('PREMIUM', 'Premium'), ('GOLD', 'Gold')])),
                ('estado', models.TextField(choices=[('ATIVO', 'Ativo'), ('ARQUIVADO', 'Arquivado')])),
            ],
        ),
    ]
